<?php

use App\Http\Controllers\Api\GameFoundationController;
use App\Http\Controllers\Api\EquipmentController;
use App\Http\Controllers\Api\ItemController;
use App\Http\Controllers\Api\LibraryController;
use App\Http\Controllers\Api\MonsterController;
use App\Http\Controllers\Api\NPCController;
use App\Http\Controllers\Api\QuestController;
use App\Http\Controllers\Api\WorldController;
use App\Http\Controllers\Api\EconomyController;
use App\Http\Controllers\Api\StoryController;
use App\Http\Controllers\Api\ProductionController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/lore/ages', [GameFoundationController::class, 'ages']);
Route::get('/lore/realms', [GameFoundationController::class, 'realms']);
Route::get('/nilalang/orders', [GameFoundationController::class, 'nilalangOrders']);
Route::get('/affiliations', [GameFoundationController::class, 'affiliations']);
Route::get('/classes', [GameFoundationController::class, 'combatClasses']);
Route::get('/trust-methods', [GameFoundationController::class, 'trustMethods']);
Route::get('/growth-system', [GameFoundationController::class, 'growthSystem']);
Route::get('/game-foundation', [GameFoundationController::class, 'foundation']);

Route::get('/libraries', [LibraryController::class, 'index']);
Route::get('/libraries/affiliations', [LibraryController::class, 'affiliations']);
Route::get('/libraries/combat-classes', [LibraryController::class, 'combatClasses']);
Route::get('/libraries/nilalang-orders', [LibraryController::class, 'nilalangOrders']);
Route::get('/libraries/personality-traits', [LibraryController::class, 'personalityTraits']);
Route::get('/libraries/ai-behaviors', [LibraryController::class, 'aiBehaviors']);
Route::get('/libraries/temperaments', [LibraryController::class, 'temperaments']);
Route::get('/libraries/status-effects', [LibraryController::class, 'statusEffects']);
Route::get('/libraries/trust-methods', [LibraryController::class, 'trustMethods']);
Route::get('/libraries/habitats', [LibraryController::class, 'habitats']);
Route::get('/libraries/weather-types', [LibraryController::class, 'weatherTypes']);
Route::get('/libraries/active-times', [LibraryController::class, 'activeTimes']);
Route::get('/libraries/rarity-tiers', [LibraryController::class, 'rarityTiers']);
Route::get('/libraries/growth-ranks', [LibraryController::class, 'growthRanks']);
Route::get('/libraries/equipment-categories', [LibraryController::class, 'equipmentCategories']);
Route::get('/libraries/item-categories', [LibraryController::class, 'itemCategories']);
Route::get('/libraries/skill-categories', [LibraryController::class, 'skillCategories']);
Route::get('/libraries/target-types', [LibraryController::class, 'targetTypes']);
Route::get('/libraries/damage-types', [LibraryController::class, 'damageTypes']);
Route::get('/libraries/{library}', [LibraryController::class, 'show']);

Route::get('/monsters/filter', [MonsterController::class, 'filter']);
Route::get('/monsters/slug/{slug}', [MonsterController::class, 'showBySlug']);
Route::get('/monsters/{monster_id}', [MonsterController::class, 'show']);
Route::get('/monsters', [MonsterController::class, 'index']);
Route::get('/monster-codex', [MonsterController::class, 'index']);
Route::get('/monster-codex/summary', [MonsterController::class, 'summary']);

Route::get('/items/search', [ItemController::class, 'search']);
Route::get('/items/categories', [ItemController::class, 'categories']);
Route::get('/items/crafting-materials', fn (Request $request, ItemController $controller) => $controller->byType('crafting_material', $request));
Route::get('/items/monster-drops', fn (Request $request, ItemController $controller) => $controller->byType('monster_drop', $request));
Route::get('/items/offerings', fn (Request $request, ItemController $controller) => $controller->byType('offering', $request));
Route::get('/items/quest-items', fn (Request $request, ItemController $controller) => $controller->byType('quest_item', $request));
Route::get('/items/slug/{slug}', [ItemController::class, 'showBySlug']);
Route::get('/items/category/{category}', [ItemController::class, 'category']);
Route::get('/items/{item_id}', [ItemController::class, 'show']);
Route::get('/items', [ItemController::class, 'index']);
Route::get('/item-codex/summary', [ItemController::class, 'summary']);

Route::get('/equipment/search', [EquipmentController::class, 'search']);
Route::get('/equipment/categories', [EquipmentController::class, 'categories']);
Route::get('/equipment/sets', [EquipmentController::class, 'sets']);
Route::get('/equipment/sets/{set_id}', [EquipmentController::class, 'set']);
Route::get('/equipment/slug/{slug}', [EquipmentController::class, 'showBySlug']);
Route::get('/equipment/category/{category}', [EquipmentController::class, 'category']);
Route::get('/equipment/slot/{slot}', [EquipmentController::class, 'slot']);
Route::get('/equipment/{equipment_id}', [EquipmentController::class, 'show']);
Route::get('/equipment', [EquipmentController::class, 'index']);
Route::get('/equipment-codex/summary', [EquipmentController::class, 'summary']);

Route::get('/npcs/search', [NPCController::class, 'search']);
Route::get('/npcs/categories', [NPCController::class, 'categories']);
Route::get('/npcs/roles', [NPCController::class, 'roles']);
Route::get('/npcs/factions', [NPCController::class, 'factions']);
Route::get('/npcs/ambient', [NPCController::class, 'ambient']);
Route::get('/npcs/shopkeepers', [NPCController::class, 'shopkeepers']);
Route::get('/npcs/trainers', [NPCController::class, 'trainers']);
Route::get('/npcs/companions', [NPCController::class, 'companions']);
Route::get('/npcs/schedule/{npc_id}', [NPCController::class, 'schedule']);
Route::get('/npcs/dialogue/{npc_id}', [NPCController::class, 'dialogue']);
Route::get('/npcs/region/{region}', [NPCController::class, 'region']);
Route::get('/npcs/faction/{faction}', [NPCController::class, 'faction']);
Route::get('/npcs/role/{role}', [NPCController::class, 'role']);
Route::get('/npcs/{npc_id}', [NPCController::class, 'show']);
Route::get('/npcs', [NPCController::class, 'index']);
Route::get('/npc-codex/summary', [NPCController::class, 'summary']);

Route::get('/quests/search', [QuestController::class, 'index']);
Route::get('/quests/categories', [QuestController::class, 'categories']);
Route::get('/quests/chains', [QuestController::class, 'chains']);
Route::get('/quests/active', [QuestController::class, 'active']);
Route::get('/quests/available', [QuestController::class, 'available']);
Route::get('/quests/completed', [QuestController::class, 'completed']);
Route::get('/quests/chain/{chain_id}', [QuestController::class, 'chain']);
Route::get('/quests/slug/{slug}', [QuestController::class, 'showBySlug']);
Route::get('/quests/category/{category}', [QuestController::class, 'category']);
Route::get('/quests/type/{type}', [QuestController::class, 'type']);
Route::post('/quests/{quest_id}/start', [QuestController::class, 'start']);
Route::post('/quests/{quest_id}/advance', [QuestController::class, 'advance']);
Route::post('/quests/{quest_id}/complete', [QuestController::class, 'complete']);
Route::post('/quests/{quest_id}/choose-branch', [QuestController::class, 'chooseBranch']);
Route::get('/quests/{quest_id}', [QuestController::class, 'show']);
Route::get('/quests', [QuestController::class, 'index']);
Route::get('/quest-codex/summary', [QuestController::class, 'summary']);

Route::get('/world/regions', [WorldController::class, 'regions']);
Route::get('/world/provinces', [WorldController::class, 'provinces']);
Route::get('/world/locations/slug/{slug}', [WorldController::class, 'showBySlug']);
Route::get('/world/locations/type/{type}', [WorldController::class, 'type']);
Route::get('/world/locations/{location_id}', [WorldController::class, 'show']);
Route::get('/world/locations', [WorldController::class, 'locations']);
Route::get('/world/routes', [WorldController::class, 'routes']);
Route::get('/world/spawns/{location_id}', [WorldController::class, 'spawns']);
Route::get('/world/npcs/{location_id}', [WorldController::class, 'npcs']);
Route::get('/world/fast-travel', [WorldController::class, 'fastTravel']);
Route::get('/world/events', [WorldController::class, 'events']);
Route::get('/world-codex/summary', [WorldController::class, 'summary']);

Route::get('/economy/currencies', [EconomyController::class, 'currencies']);
Route::get('/economy/stations', [EconomyController::class, 'stations']);
Route::get('/economy/recipes', [EconomyController::class, 'recipes']);
Route::get('/economy/recipes/{recipe_id}', [EconomyController::class, 'recipe']);
Route::get('/economy/shops', [EconomyController::class, 'shops']);
Route::get('/economy/shops/{shop_id}/inventory', [EconomyController::class, 'inventory']);
Route::get('/economy/shops/{shop_id}', [EconomyController::class, 'shop']);
Route::get('/economy/trade-routes', [EconomyController::class, 'tradeRoutes']);
Route::get('/economy/festival-markets', [EconomyController::class, 'festivalMarkets']);
Route::get('/economy/events', [EconomyController::class, 'events']);
Route::post('/economy/craft/{recipe_id}', [EconomyController::class, 'craft']);
Route::post('/economy/buy', [EconomyController::class, 'buy']);
Route::post('/economy/sell', [EconomyController::class, 'sell']);
Route::post('/economy/barter', [EconomyController::class, 'barter']);
Route::get('/economy-codex/summary', [EconomyController::class, 'summary']);

Route::get('/story/acts', [StoryController::class, 'acts']);
Route::get('/story/chapters', [StoryController::class, 'chapters']);
Route::get('/story/scenes', [StoryController::class, 'scenes']);
Route::get('/story/dialogues', [StoryController::class, 'dialogues']);
Route::get('/story/timeline', [StoryController::class, 'timeline']);
Route::get('/story/lore', [StoryController::class, 'lore']);
Route::get('/story/endings', [StoryController::class, 'endings']);
Route::get('/story/mythology', [StoryController::class, 'mythology']);
Route::get('/story/relationships', [StoryController::class, 'relationships']);
Route::get('/story-codex/summary', [StoryController::class, 'summary']);

Route::get('/production/summary', [ProductionController::class, 'summary']);
Route::get('/production/import-status', [ProductionController::class, 'importStatus']);
Route::post('/production/import', [ProductionController::class, 'runImport']);
Route::get('/production/export-jobs', [ProductionController::class, 'exportJobs']);
Route::post('/production/export', [ProductionController::class, 'runExport']);
Route::get('/production/validation-reports', [ProductionController::class, 'validationReports']);
Route::post('/production/validate', [ProductionController::class, 'runValidation']);
Route::get('/production/assets', [ProductionController::class, 'assets']);
Route::post('/production/assets', [ProductionController::class, 'registerAsset']);
Route::post('/production/prompts', [ProductionController::class, 'generatePrompt']);
Route::get('/production/localization', [ProductionController::class, 'localization']);
Route::get('/production/build-status', [ProductionController::class, 'buildStatus']);
Route::get('/production/qa-reports', [ProductionController::class, 'qaReports']);
Route::get('/production/analytics-summary', [ProductionController::class, 'analyticsSummary']);
Route::get('/production/mod-packs', [ProductionController::class, 'modPacks']);
Route::post('/production/developer-command', [ProductionController::class, 'developerCommand']);
